services:
    msgcontrol:
        build:
            context: .
            dockerfile: Dockerfile.msgcontrol
        depends_on:
            database:
                condition: service_started
            broker:
                condition: service_started

    httpcontrol:
        ports:
            - "80:80"
        build:
            context: .
            dockerfile: Dockerfile.httpcontrol
        environment:
            HTTP_CLIENTS_FILE: /secrets/httpclients.json
            GIN_MODE: release
        volumes:
            - ${HOST_HTTP_CLIENTS_FILE}:/secrets/httpclients.json
        depends_on:
            database:
                condition: service_started

    database:  
        image: redis
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        
    broker:
        image: eclipse-mosquitto:2.0
        ports:
            - "1883:1883"
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
